name: 5300-env-small
channels:
- conda-forge
dependencies:
- python
- nb_conda_kernels
- numpy
- scipy
- matplotlib
- pandas
- seaborn
- jupyter
- ipywidgets
- nbdime
- mkl-service
- jupyter_nbextensions_configurator
- pydoe
